id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Amish Dev'
  social:
    -
      name: Github
      url: 'https://github.com/amishdev'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:_@christians.email'
      icon: site/social-icons/email.svg
